// <auto-generated />
namespace PodcastMonitor.DataModel.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddFeedSetsAndUsers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddFeedSetsAndUsers));
        
        string IMigrationMetadata.Id
        {
            get { return "201304062103447_AddFeedSetsAndUsers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
