// <auto-generated />
namespace PodcastsDataModel.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Feeds_AddCategory : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Feeds_AddCategory));
        
        string IMigrationMetadata.Id
        {
            get { return "201304012053186_Feeds_AddCategory"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
