// <auto-generated />
namespace PodcastsDataModel.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Category_AddLengthToName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Category_AddLengthToName));
        
        string IMigrationMetadata.Id
        {
            get { return "201304012106050_Category_AddLengthToName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
