// <auto-generated />
namespace PodcastModel.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class first_stuff : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(first_stuff));
        
        string IMigrationMetadata.Id
        {
            get { return "201303101628024_first_stuff"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
