// <auto-generated />
namespace PodcastModel.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Feed_AddUri : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Feed_AddUri));
        
        string IMigrationMetadata.Id
        {
            get { return "201303101631532_Feed_AddUri"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
