// <auto-generated />
namespace PodcastModel.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Feed_AddNewFields : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Feed_AddNewFields));
        
        string IMigrationMetadata.Id
        {
            get { return "201303271502361_Feed_AddNewFields"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
